version: 2

models:
  - name: hospital_charges
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: cpt_id
        tests:
          - not_null
          - relationships:
              to: ref('cpt_codes')
              field: cpt_id
      - name: payer_id
        tests:
          - relationships:
              to: ref('payers')
              field: payer_id
      - name: location_id
        tests:
          - relationships:
              to: ref('locations')
              field: location_id
      - name: hospital_id
        tests:
          - not_null
          - relationships:
              to: ref('hospitals')
              field: hospital_id

  - name: cpt_codes
    columns:
      - name: cpt_id
        tests:
          - unique
          - not_null
      - name: cpt_code
        tests:
          - unique
          - not_null
      - name: description

  - name: payers
    columns:
      - name: payer_id
        tests:
          - unique
          - not_null
      - name: payer
        tests:
          - unique
          - not_null

  - name: locations
    columns:
      - name: location_id
        tests:
          - unique
          - not_null
      - name: state
        tests:
          - not_null
      - name: city
        tests:
          - not_null
      - name: zipcode
        tests:
          - not_null

  - name: payer_locations
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: payer_id
        tests:
          - not_null
          - relationships:
              to: ref('payers')
              field: payer_id
      - name: location_id
        tests:
          - not_null
          - relationships:
              to: ref('locations')
              field: location_id

  - name: hospitals
    columns:
      - name: hospital_id
        tests:
          - unique
          - not_null
      - name: hospital
        tests:
          - unique
          - not_null