version: 2

sources:
  - name: staging_db
    database: "{{ var('source_database') }}"
    schema: staging_db
    tables:
      - name: staging_table
        identifier: "{{ var('staging_table') }}"

  - name: intermediate_cleaning
    database: "{{ target.database }}"
    schema: _intermediate_cleaning
    tables:
      - name: cpt-translation
      - name: code_mappings
        identifier: "*_code_mappings"

  - name: seeds
    database: "{{ target.database }}"
    schema: _intermediate_cleaning
    tables:
      - name: code_mappings
        identifier: "*_code_mappings"