name: 'hospital_pricing'
version: '1.0.0'
config-version: 2

profile: 'hospital_pricing'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  hospital_pricing:
    schema: intermediate_cleaning
    cpt_translation:
      +column_types:
        "CPT Code": varchar(5)
        Description: text
    code_mappings:
      +enabled: true
      +schema: intermediate_cleaning
      +column_types:
        "Diagnosis Code": varchar(8)
        Description: text

models:
  hospital_pricing:
    +database: "{{ target.database }}"
    staging:
      +materialized: table
      +schema: intermediate_cleaning
    intermediate:
      +materialized: table
      +schema: clean_data
    warehouse:
      +materialized: table
      +schema: warehouse
      +persist_docs:
        relation: true
    production:
      +materialized: incremental
      +schema: production_db
      +database: production_db

vars:
  source_database: staging_db
  staging_table: staging_table